dbt_pipeline:
  target: dev
  outputs:
    dev:
      type: mysql
      host: mysql-db
      port: 3306
      database: test_db
      schema: test_db
      username: root
      password: password
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql
      host: mysql-db
      port: 3306
      database: test_db
      schema: test_db
      username: root
      password: password
      driver: MySQL ODBC 8.0 ANSI Driver