dbt_pipeline:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3307
      database: test_db
      schema: test_db
      username: root
      password: password
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql
      server: localhost
      port: 3307
      database: test_db
      schema: test_db
      username: root
      password: password
      driver: MySQL ODBC 8.0 ANSI Driver